site_name: SmartHome Documentation
theme: readthedocs
markdown_extensions:
  - md_in_html
  - plantuml_markdown
plugins:
  - swagger-ui-tag
  - search
  - include-markdown
  - asyncapi-tag
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
